# **1- import libraries**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

In [2]:
df = pd.read_csv('data.csv')
df

,price,brand,model,year,condition,kilo_meter,color,power_trans,fuel_type,location,price_bin
0,2000000.0,Cadillac,Escalade,2018,Used,"185,000 KM",Black,Automatic,Diesel,Tagamo3 - New Cairo,0.7
1,2000000.0,Seat,Tarraco,2024,Used,"45,000 KM",Black,Automatic,Gas,Cairo,0.7
2,1050000.0,Toyota,Corolla,2020,Used,"44,000 KM",White,Automatic,Gas,Nasr city,0.3
3,1120000.0,Skoda,Octavia,2020,Used,"125,000 KM",Gray,Automatic,Gas,Nasr city,0.4
4,1020000.0,Hyundai,Elantra,2027,New,0 KM,Dark blue,Automatic,Gas,Mohandessin,0.3
...,...,...,...,...,...,...,...,...,...,...,...
20456,1385000.0,Toyota,Corolla,2025,Used,"10,000",Gray,Automatic,Benzine,Giza,0.5
20457,620000.0,Kia,Rio,2017,Used,"135,000",Brown,Automatic,Benzine,Nasr City,0.2
20458,1795000.0,Deepal,S07,2024,New,0,Gray,Automatic,Electric,Cairo,0.6
20459,770000.0,Chrysler,Town and Country,2010,Used,"300,000",Gray,Automatic,Benzine,Cairo,0.2
20460,1750000.0,Mercedes-Benz,C180,2018,Used,"128,000",White,Automatic,Benzine,Cairo,0.6

In [3]:
df.shape

(20461, 11)

In [4]:
df.head()

,price,brand,model,year,condition,kilo_meter,color,power_trans,fuel_type,location,price_bin
0,2000000.0,Cadillac,Escalade,2018,Used,"185,000 KM",Black,Automatic,Diesel,Tagamo3 - New Cairo,0.7
1,2000000.0,Seat,Tarraco,2024,Used,"45,000 KM",Black,Automatic,Gas,Cairo,0.7
2,1050000.0,Toyota,Corolla,2020,Used,"44,000 KM",White,Automatic,Gas,Nasr city,0.3
3,1120000.0,Skoda,Octavia,2020,Used,"125,000 KM",Gray,Automatic,Gas,Nasr city,0.4
4,1020000.0,Hyundai,Elantra,2027,New,0 KM,Dark blue,Automatic,Gas,Mohandessin,0.3

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20461 entries, 0 to 20460
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   price        20461 non-null  float64
 1   brand        20461 non-null  str
 2   model        20461 non-null  str
 3   year         20461 non-null  str
 4   condition    20461 non-null  str
 5   kilo_meter   20461 non-null  str
 6   color        20461 non-null  str
 7   power_trans  20461 non-null  str
 8   fuel_type    20461 non-null  str
 9   location     20461 non-null  str
 10  price_bin    20461 non-null  float64
dtypes: float64(2), str(9)
memory usage: 2.8 MB

--------> All columns are string data type

# **2- check missing & duplications**

In [6]:
df.isnull().sum()

price          0
brand          0
model          0
year           0
condition      0
kilo_meter     0
color          0
power_trans    0
fuel_type      0
location       0
price_bin      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

### --------> No Missing Value and find **1014** Duplicated rows

### --------> Delete duplicated data

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df.duplicated().sum()

np.int64(0)

# Check outliers

In [10]:
# Convert price column to numeric and Chick outliers
df['price'] = (
    df['price']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('EGP', '', regex=False)
    .str.strip()
)

df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [11]:
fig = px.box(
    df,
    x='price',
    title='Car Price Distribution After Removing Outliers'
)

fig.show()

# Handel Ouliers

In [12]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [13]:
df = df[
    (df['price'] >= lower) &
    (df['price'] <= upper)
]

In [14]:
df['price_bin'] = pd.cut(
    df['price'],
    bins=10,
    labels=False
)
df['price_bin'] = df['price_bin'] / 10
df['price_bin'].value_counts()

price_bin
0.1    4309
0.2    3532
0.3    3011
0.0    2952
0.4    1849
0.5    1539
0.6     884
0.7     801
0.8     612
0.9     537
Name: count, dtype: int64

In [15]:
pd.set_option("display.max_rows", None)

print(df["color"].value_counts())

color
Black                           3564
Silver                          3062
White                           2678
Gray                            2431
Red                             1722
Blue- Navy Blue                  832
Dark blue                        761
Blue                             759
Dark grey                        556
Dark red                         466
Gold                             442
Green                            430
Burgundy                         293
Bronze                           287
Brown                            271
Petroleum                        233
Other                            169
Mocha                            133
Beige                            118
?????                            104
Other Color                       92
Dark green                        86
Cyan                              84
Orange                            56
Yellow                            55
??????                            52
????                              52
Eggplant                          45
Champagne                         30
Olive                             29
????? ????                        18
???                               12
Purple                            11
??? ????                           6
???? ?????                         5
???? ????                          5
?????? ????                        4
???? ??????                        4
???????                            4
Sky blue                           3
Pepsi                              2
gray                               2
?????? ??????                      2
Dark gray                          2
ocean blue                         1
navy blue                          1
Dark gery                          1
Sonic Grey                         1
what                               1
??????? ???                        1
Grey Magno Matte                   1
Ash gray                           1
other                              1
metallic grey                      1
Light blue                         1
rose                               1
Cyber silver and eclipse red       1
Blue black                         1
Black and silver                   1
dark red with black                1
Dark Grey                          1
light blue                         1
??? ?? ???????                     1
dark Gray                          1
Grey                               1
????? ? ????                       1
Black Silver                       1
Grey in red                        1
Light Blue                         1
?? ?????                           1
silver                             1
????? ???? ??????                  1
Amazon grey                        1
Indigo Sunset Blue                 1
Dark Brown                         1
burgandi                           1
white                              1
??? ????- ????                     1
Dark olive                         1
Amazon Gray                        1
??? ?????                          1
??? ???????                        1
petrolly                           1
Gray black                         1
????*????                          1
01227658192 ????                   1
magnesium green                    1
Mineral Gray Metallic              1
champin                            1
sky                                1
???? ? ????                        1
???? ???????                       1
Steel Grey                         1
Navy                               1
????? ??????                       1
Waveblue                           1
Black * olive green                1
Red & Black 2 Tone                 1
Name: count, dtype: int64

In [16]:
import re

def clean_color(color):

    if pd.isna(color):
        return "Unknown"

    color = str(color).strip().lower()

    # =========================
    # INVALID / CORRUPTED
    # =========================
    if "?" in color:
        return "Unknown"

    if any(x in color for x in [
        "01227658192",
        "what"
    ]):
        return "Unknown"

    # =========================
    # BLACK
    # =========================
    if "black" in color:
        return "Black"

    # =========================
    # WHITE
    # =========================
    if "white" in color:
        return "White"

    # =========================
    # SILVER
    # =========================
    if "silver" in color:
        return "Silver"

    # =========================
    # GRAY
    # =========================
    if any(x in color for x in [
        "gray",
        "grey",
        "gery",
        "magno",
        "sonic grey",
        "amazon grey",
        "amazon gray",
        "mineral gray",
        "steel grey",
        "ash gray"
    ]):
        return "Gray"

    # =========================
    # RED
    # =========================
    if "red" in color:
        return "Red"

    # =========================
    # BLUE
    # =========================
    if "blue" in color:
        if "navy" in color:
            return "Navy"
        elif "light" in color or "sky" in color:
            return "Light Blue"
        elif "dark" in color:
            return "Dark Blue"
        else:
            return "Blue"

    if "navy" in color:
        return "Navy"

    if "cyan" in color:
        return "Blue"

    # =========================
    # GREEN
    # =========================
    if "green" in color:
        if "dark" in color:
            return "Dark Green"
        return "Green"

    if "olive" in color:
        return "Olive"

    # =========================
    # PURPLE
    # =========================
    if "purple" in color or "eggplant" in color:
        return "Purple"

    # =========================
    # BROWN
    # =========================
    if "brown" in color or "mocha" in color:
        return "Brown"

    # =========================
    # BEIGE
    # =========================
    if "beige" in color:
        return "Beige"

    # =========================
    # GOLD
    # =========================
    if "gold" in color:
        return "Gold"

    # =========================
    # BRONZE
    # =========================
    if "bronze" in color:
        return "Bronze"

    # =========================
    # ORANGE
    # =========================
    if "orange" in color:
        return "Orange"

    # =========================
    # YELLOW
    # =========================
    if "yellow" in color:
        return "Yellow"

    # =========================
    # BURGUNDY
    # =========================
    if "burgand" in color or "burgundy" in color:
        return "Burgundy"

    # =========================
    # CHAMPAGNE
    # =========================
    if "champ" in color:
        return "Champagne"

    # =========================
    # PETROLEUM
    # =========================
    if "petrol" in color or "petroleum" in color:
        return "Petroleum"

    # =========================
    # ROSE
    # =========================
    if "rose" in color:
        return "Rose"

    # =========================
    # OTHER
    # =========================
    if "other" in color:
        return "Other"

    # =========================
    # UNKNOWN
    # =========================
    return "Unknown"

In [17]:
df["color"] = df["color"].apply(clean_color)

In [18]:
print(df["color"].value_counts())

color
Black         3571
Silver        3064
Gray          3004
White         2679
Red           2188
Blue           846
Navy           834
Dark Blue      761
Gold           442
Green          431
Brown          405
Burgundy       294
Bronze         287
Unknown        285
Other          262
Petroleum      234
Beige          118
Dark Green      86
Purple          56
Orange          56
Yellow          55
Champagne       31
Olive           30
Light Blue       6
Rose             1
Name: count, dtype: int64

## Visualizaion In file **cars_dash.py**

In [19]:
df.to_csv('data.csv', index=False, encoding='utf-8-sig')