# **1- import libraries**

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import plotly.express as px
import seaborn as sns

In [2]:
df = pd.read_csv('data.csv')
df

,price,brand,model,year,condition,kilo_meter,color,power_trans,fuel_type,location,price_bin
0,2000000.0,Cadillac,Escalade,2018,Used,"185,000 KM",Black,Automatic,Diesel,Tagamo3 - New Cairo,0.5
1,2000000.0,Seat,Tarraco,2024,Used,"45,000 KM",Black,Automatic,Gas,Cairo,0.5
2,2850000.0,Mercedes,CLA 200,2024,New,0 KM,White,Automatic,Gas,Sheikh Zayed City,0.8
3,1050000.0,Toyota,Corolla,2020,Used,"44,000 KM",White,Automatic,Gas,Nasr city,0.2
4,1120000.0,Skoda,Octavia,2020,Used,"125,000 KM",Gray,Automatic,Gas,Nasr city,0.3
...,...,...,...,...,...,...,...,...,...,...,...
21632,1385000.0,Toyota,Corolla,2025,Used,"10,000",Gray,Automatic,Benzine,Giza,0.3
21633,620000.0,Kia,Rio,2017,Used,"135,000",Brown,Automatic,Benzine,Nasr City,0.1
21634,1795000.0,Deepal,S07,2024,New,0,Gray,Automatic,Electric,Cairo,0.5
21635,770000.0,Chrysler,Town and Country,2010,Used,"300,000",Gray,Automatic,Benzine,Cairo,0.2
21636,1750000.0,Mercedes-Benz,C180,2018,Used,"128,000",White,Automatic,Benzine,Cairo,0.4

In [3]:
df.shape

(21637, 11)

In [4]:
df.head()

,price,brand,model,year,condition,kilo_meter,color,power_trans,fuel_type,location,price_bin
0,2000000.0,Cadillac,Escalade,2018,Used,"185,000 KM",Black,Automatic,Diesel,Tagamo3 - New Cairo,0.5
1,2000000.0,Seat,Tarraco,2024,Used,"45,000 KM",Black,Automatic,Gas,Cairo,0.5
2,2850000.0,Mercedes,CLA 200,2024,New,0 KM,White,Automatic,Gas,Sheikh Zayed City,0.8
3,1050000.0,Toyota,Corolla,2020,Used,"44,000 KM",White,Automatic,Gas,Nasr city,0.2
4,1120000.0,Skoda,Octavia,2020,Used,"125,000 KM",Gray,Automatic,Gas,Nasr city,0.3

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21637 entries, 0 to 21636
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   price        21637 non-null  float64
 1   brand        21637 non-null  str
 2   model        21637 non-null  str
 3   year         21637 non-null  str
 4   condition    21637 non-null  str
 5   kilo_meter   21637 non-null  str
 6   color        21637 non-null  str
 7   power_trans  21637 non-null  str
 8   fuel_type    21637 non-null  str
 9   location     21637 non-null  str
 10  price_bin    21637 non-null  float64
dtypes: float64(2), str(9)
memory usage: 2.9 MB

--------> All columns are string data type

# **2- check missing & duplications**

In [6]:
df.isnull().sum()

price          0
brand          0
model          0
year           0
condition      0
kilo_meter     0
color          0
power_trans    0
fuel_type      0
location       0
price_bin      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

### --------> No Missing Value and find **1014** Duplicated rows

### --------> Delete duplicated data

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df.duplicated().sum()

np.int64(0)

# Check outliers

In [10]:
# Convert price column to numeric and Chick outliers
df['price'] = (
    df['price']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.replace('EGP', '', regex=False)
    .str.strip()
)

df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [11]:
fig = px.box(
    df,
    x='price',
    title='Car Price Distribution After Removing Outliers'
)

fig.show()

# Handel Ouliers

In [12]:
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [13]:
df = df[
    (df['price'] >= lower) &
    (df['price'] <= upper)
]

In [14]:
df['price_bin'] = pd.cut(
    df['price'],
    bins=10,
    labels=False
)
df['price_bin'] = df['price_bin'] / 10
df['price_bin'].value_counts()

price_bin
0.1    4326
0.2    4159
0.0    3534
0.3    2496
0.4    1942
0.5    1367
0.6     870
0.7     777
0.8     548
0.9     442
Name: count, dtype: int64

In [15]:
df['price_bin'].value_counts().sort_index()

price_bin
0.0    3534
0.1    4326
0.2    4159
0.3    2496
0.4    1942
0.5    1367
0.6     870
0.7     777
0.8     548
0.9     442
Name: count, dtype: int64

In [16]:
pd.cut(
    df['price'],
    bins=10
).value_counts().sort_index()

price
(-1689.0, 269900.0]       3534
(269900.0, 538800.0]      4326
(538800.0, 807700.0]      4159
(807700.0, 1076600.0]     2496
(1076600.0, 1345500.0]    1942
(1345500.0, 1614400.0]    1367
(1614400.0, 1883300.0]     870
(1883300.0, 2152200.0]     777
(2152200.0, 2421100.0]     548
(2421100.0, 2690000.0]     442
Name: count, dtype: int64

In [17]:
for b in sorted(df['price_bin'].dropna().unique()):
    print(f"\n===== BIN {b} =====")
    print(df[df['price_bin'] == b][
        ['price', 'brand', 'model', 'year', 'condition']
    ].head(10))

===== BIN 0.0 =====
        price       brand            model  year condition
13   150000.0        Fiat           Shahin  2006      Used
35   150000.0        Seat            Ibiza  1998      Used
45   250000.0    Daihatsu         Gran max  2011      Used
55   160000.0     Hyundai            Excel  1993      Used
56    60000.0      Citro雗               Ax  1996      Used
76   230000.0      Daewoo          Leganza  2002      Used
88   250000.0      Toyota             Echo  2000      Used
120  225000.0  Mitsubishi  Lancer Crystala  1998      Used
122  170000.0      Toyota         Cressida  1983      Used
154  200000.0     Renault             Clio  2003      Used

===== BIN 0.1 =====
       price      brand     model  year condition
19  350000.0        Byd        F3  2015      Used
36  350000.0     Suzuki      Alto  2019      Used
38  430000.0        Byd        F3  2019      Used
39  490000.0  Chevrolet      Aveo  2019      Used
47  280000.0     Daewoo  Nubira 2  1999      Used
48  520000.0        Jac        J7  2022      Used
77  280000.0  Chevrolet      Aveo  2008      Used
78  280000.0  Chevrolet      Aveo  2008      Used
79  420000.0    Renault   Sandero  2016      Used
82  460000.0    Renault    Megane  2012      Used

===== BIN 0.2 =====
       price    brand        model  year condition
8   730000.0       MG            5  2021      Used
11  760000.0     Ford        Focus  2018      Used
12  585000.0     Opel        Astra  2017      Used
14  650000.0   Suzuki  Swift Dzire  2022       New
15  680000.0  Renault       Megane  2019      Used
16  580000.0    Chery     Arrizo 5  2023      Used
18  720000.0   Nissan        Sunny  2022      Used
24  545000.0      Kia       Cerato  2011      Used
34  660000.0   Citro雗     C Elysee  2021      Used
40  650000.0     Opel    Crossland  2018      Used

===== BIN 0.3 =====
        price    brand    model  year condition
3   1050000.0   Toyota  Corolla  2020      Used
5   1020000.0  Hyundai  Elantra  2027       New
9    830000.0     Opel    Mokka  2022      Used
20   870000.0   Citro雗       C5  2021      Used
23   830000.0       MG       ZS  2022      Used
33  1019000.0  Peugeot     2008  2021      Used
37   870000.0   Nissan  Qashqai  2019      Used
44   890000.0   Nissan   Sentra  2025      Used
52  1050000.0      BMW      318  2018      Used
57   890000.0       Ds      DS3  2021      Used

===== BIN 0.4 =====
         price       brand        model  year condition
4    1120000.0       Skoda      Octavia  2020      Used
21   1150000.0         Kia        Xceed  2022      Used
22   1185000.0    Mercedes      GLK 300  2010      Used
46   1300000.0     Changan        UNI-T  2025       New
65   1149000.0     Hyundai   Tucson GDI  2017      Used
67   1100000.0     Hyundai      Elantra  2027       New
96   1080000.0  Volkswagen       Golf R  2014      Used
106  1150000.0      Citro雗  C5 Aircross  2021      Used
113  1300000.0     Hyundai      Elantra  2024      Used
130  1090000.0     Hyundai   Tucson GDI  2017      Used

===== BIN 0.5 =====
         price       brand           model  year condition
17   1420000.0    Mercedes             180  2014      Used
31   1400000.0       Geely        City Ray  2026      Used
51   1350000.0    Chrysler  Town & Country  2006      Used
62   1370000.0  Volkswagen          Golf 6  2022      Used
66   1360000.0      Toyota         Corolla  2026       New
72   1500000.0       Volvo            XC60  2019      Used
105  1490000.0      Nissan         Qashqai  2025      Used
133  1530000.0  Volkswagen            ID 4  2024      Used
138  1600000.0      Jetour             X90  2027       New
139  1350000.0      Jetour         Dashing  2027       New

===== BIN 0.6 =====
         price       brand       model  year condition
6    1630000.0       Geely    EX5 EM-i  2027       New
7    1700000.0       Skoda     Octavia  2023      Used
10   1650000.0         KGM      Torres  2024      Used
25   1780000.0      Toyota     Corolla  2026       New
27   1750000.0  Mitsubishi      Pajero  2016      Used
59   1850000.0    Mercedes       C 180  2019      Used
69   1840000.0     Hyundai  Tucson GDI  2026       New
92   1850000.0     Peugeot         408  2023      Used
101  1840000.0         Kia    Sportage  2027       New
111  1680000.0       Volvo       XC 40  2021      Used

===== BIN 0.7 =====
         price     brand       model  year condition
0    2000000.0  Cadillac    Escalade  2018      Used
1    2000000.0      Seat     Tarraco  2024      Used
26   1890000.0   Hyundai  Tucson GDI  2027       New
28   2000000.0     Skoda      Superb  2023      Used
29   2120000.0   Peugeot         408  2026      Used
41   2150000.0       Kia    Sportage  2024      Used
50   1970000.0     Tesla     Model S  2018      Used
54   1900000.0       BMW         520  2018      Used
60   2000000.0  Mercedes       C 180  2018      Used
109  1950000.0       Byd   Sealion 6  2026       New

===== BIN 0.8 =====
         price       brand       model  year condition
32   2400000.0  Volkswagen      Tiguan  2026      Used
49   2399990.0     Peugeot        3008  2026       New
226  2250000.0         Byd      Song L  2025       New
261  2280000.0       Cupra    Terramar  2026       New
266  2350000.0    Mercedes       C 180  2020      Used
327  2350000.0       Skoda      Superb  2026       New
334  2200000.0       Isuzu         NPR  2026       New
336  2350000.0       Cupra    Terramar  2026       New
378  2200000.0     Peugeot         408  2027       New
384  2340000.0     Hyundai  Tucson GDI  2025       New

===== BIN 0.9 =====
         price       brand   model  year condition
53   2550000.0    Mercedes   C 180  2022      Used
94   2666000.0       Avatr       6  2026       New
95   2555000.0       Avatr      07  2026       New
102  2600000.0       Avatr      12  2026      Used
103  2560000.0  Volkswagen  Tiguan  2026       New
159  2560000.0       Skoda  Kodiaq  2026      Used
169  2499000.0       Avatr      07  2026       New
185  2540000.0       Skoda  Kodiaq  2025      Used
193  2550000.0  Volkswagen  Tiguan  2026      Used
252  2450000.0       Skoda  Kodiaq  2024      Used

## Visualizaion In file **cars_dash.py**

In [ ]:
# df.to_csv('data.csv', index=False, encoding='utf-8-sig')

In [19]:
df.head()

,price,brand,model,year,condition,kilo_meter,color,power_trans,fuel_type,location,price_bin
0,2000000.0,Cadillac,Escalade,2018,Used,"185,000 KM",Black,Automatic,Diesel,Tagamo3 - New Cairo,0.7
1,2000000.0,Seat,Tarraco,2024,Used,"45,000 KM",Black,Automatic,Gas,Cairo,0.7
3,1050000.0,Toyota,Corolla,2020,Used,"44,000 KM",White,Automatic,Gas,Nasr city,0.3
4,1120000.0,Skoda,Octavia,2020,Used,"125,000 KM",Gray,Automatic,Gas,Nasr city,0.4
5,1020000.0,Hyundai,Elantra,2027,New,0 KM,Dark blue,Automatic,Gas,Mohandessin,0.3

In [20]:
X = df.drop(['price', 'price_bin'], axis=1)
y = df['price']

In [21]:
categorical_cols = X.select_dtypes(include="object").columns
numerical_cols = X.select_dtypes(exclude="object").columns

C:\Users\Dell\AppData\Local\Temp\ipykernel_4040\3607657429.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include="object").columns

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
global_mean = y_train.mean()

encoding_maps = {}

for col in categorical_cols:

    temp = pd.DataFrame({
        col: X_train[col],
        "price": y_train
    })

    stats = temp.groupby(col)["price"].agg(["mean", "count"])

    alpha = 10

    stats["encoded"] = (
        stats["mean"] * stats["count"] +
        global_mean * alpha
    ) / (stats["count"] + alpha)

    encoding_maps[col] = stats["encoded"].to_dict()

In [26]:
X_train_encoded = X_train.copy()

for col in categorical_cols:
    X_train_encoded[col] = (
        X_train_encoded[col]
        .map(encoding_maps[col])
        .fillna(global_mean)
    )

X_train_encoded = X_train_encoded.astype(float)

In [27]:
X_test_encoded = X_test.copy()

for col in categorical_cols:
    X_test_encoded[col] = (
        X_test_encoded[col]
        .map(encoding_maps[col])
        .fillna(global_mean)
    )

X_test_encoded = X_test_encoded.astype(float)

In [28]:
print(X_train_encoded.shape)
print(X_test_encoded.shape)

(16368, 9)
(4093, 9)

In [29]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    objective="reg:squarederror"
)

model.fit(
    X_train_encoded,
    y_train
)

print("Model trained successfully!")

Model trained successfully!

In [30]:
y_pred = model.predict(X_test_encoded)

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_test, y_pred)
)

r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:,.2f}")
print(f"RMSE: {rmse:,.2f}")
print(f"R² Score: {r2:.4f}")

MAE: 97,144.26
RMSE: 172,892.95
R² Score: 0.9171

In [34]:
model.save_model("car_price_model.json")

In [35]:
import pickle

artifacts = {
    "encoding_maps": encoding_maps,
    "global_mean": global_mean,
    "categorical_cols": list(categorical_cols)
}

with open("car_price_encoder.pkl", "wb") as file:
    pickle.dump(artifacts, file)

print("Files saved successfully!")

Files saved successfully!

In [36]:
car = {
    "brand": "Toyota",
    "model": "Corolla",
    "year": 2020,
    "condition": "Used",
    "kilo_meter": 80000,
    "color": "White",
    "power_trans": "Automatic",
    "fuel_type": "Petrol",
    "location": "Cairo"
}

new_car = pd.DataFrame([car])

In [37]:
for col in categorical_cols:
    new_car[col] = (
        new_car[col]
        .map(encoding_maps[col])
        .fillna(global_mean)
    )

new_car = new_car.astype(float)

In [38]:
predicted_price = model.predict(new_car)[0]

print(f"Predicted Price: {predicted_price:,.0f} EGP")

Predicted Price: 884,060 EGP