# **1- import libraries**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

In [2]:
df = pd.read_csv('census_income.csv')
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47568,33,Private,245211,Bachelors,13,Never-married,Prof-specialty,Own-child,White,Male,0,0,40,United-States,0
47569,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,0
47570,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,0
47571,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,0
47572,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,1

In [3]:
df['income'] = df['income'].str.strip()

df['income'] = df['income'].apply(
    lambda x: 1 if x == '>50K' or x == '>50K.' else 0
)

AttributeError: Can only use .str accessor with string values, not integer

In [4]:
df['income'].value_counts()

income
0    36038
1    11535
Name: count, dtype: int64

In [5]:
df.shape

(47573, 15)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 47573 entries, 0 to 47572
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             47573 non-null  int64
 1   workclass       47573 non-null  str
 2   fnlwgt          47573 non-null  int64
 3   education       47573 non-null  str
 4   education-num   47573 non-null  int64
 5   marital-status  47573 non-null  str
 6   occupation      47573 non-null  str
 7   relationship    47573 non-null  str
 8   race            47573 non-null  str
 9   sex             47573 non-null  str
 10  capital-gain    47573 non-null  int64
 11  capital-loss    47573 non-null  int64
 12  hours-per-week  47573 non-null  int64
 13  native-country  47573 non-null  str
 14  income          47573 non-null  int64
dtypes: int64(7), str(8)
memory usage: 8.8 MB

In [7]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [8]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week,income
count,47573.000000,4.757300e+04,47573.000000,47573.000000,47573.000000,47573.000000,47573.000000
mean,38.648771,1.897319e+05,10.091628,1092.238581,87.942131,40.603998,0.242469
std,13.556990,1.055829e+05,2.567288,7490.924415,404.204740,12.261040,0.428581
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000,0.000000
25%,28.000000,1.175850e+05,9.000000,0.000000,0.000000,40.000000,0.000000
50%,37.000000,1.782820e+05,10.000000,0.000000,0.000000,40.000000,0.000000
75%,48.000000,2.377130e+05,12.000000,0.000000,0.000000,45.000000,0.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000,1.000000

# **2- check missing & duplications**

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.dropna(inplace = True)

In [12]:
df.drop_duplicates(inplace = True)

# Visualization
https://hishamkhalil.pythonanywhere.com/

In [13]:
df.to_csv('census_income.csv', index=False, encoding='utf-8-sig')

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

# Encoding

In [15]:
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

df.head()

C:\Users\Dell\AppData\Local\Temp\ipykernel_7044\3677820764.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0

# Scaling

In [16]:
X = df.drop('income', axis = 1)
y = df['income']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
scaler = StandardScaler()

# Fit ONLY on training data
X_train = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

In [19]:
# Use the same scaler on test data
X_test = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
df['income'].value_counts()

income
0    36038
1    11535
Name: count, dtype: int64

# UnderSampling

In [20]:
!pip install imblearn
from imblearn.under_sampling import RandomUnderSampler

Requirement already satisfied: imblearn in .\.venv\Lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in .\.venv\Lib\site-packages (from imblearn) (0.14.2)
Requirement already satisfied: numpy<3,>=1.25.2 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (2.5.3)
Requirement already satisfied: scipy<2,>=1.11.4 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (1.18.1)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (1.9.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.6 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (0.1.6)
Requirement already satisfied: joblib<2,>=1.2.0 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (1.6.0)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in .\.venv\Lib\site-packages (from imbalanced-learn->imblearn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\.venv\Lib\site-packages (from joblib<2,>=1.2.0->imbalanced-learn->imblearn) (3.1.2)
Requirement already satisfied: narwhals>=2.0.1 in .\.venv\Lib\site-packages (from scikit-learn<2,>=1.4.2->imbalanced-learn->imblearn) (2.26.0)

In [21]:
rus = RandomUnderSampler(random_state=42)

X_resampled, y_resampled = rus.fit_resample(X, y)

# Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000)

params = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['lbfgs', 'liblinear']
}

grid_lr = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_lr.fit(X_train, y_train)

print('Best Parameters:', grid_lr.best_params_)
print('Best F1 Score:', grid_lr.best_score_)

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

Detailed tracebacks of the workers should have been printed to stderr in the executor process if faulthandler was not disabled.

# KNeighborsClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

params = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}

grid_knn = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_knn.fit(X_train, y_train)

print('Best Parameters:', grid_knn.best_params_)
print('Best F1 Score:', grid_knn.best_score_)

Best Parameters: {'n_neighbors': 11, 'p': 1, 'weights': 'uniform'}
Best F1 Score: 0.7922951869328221

# SVC

In [44]:
from sklearn.svm import SVC

model = SVC()

params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf'],
    'gamma': [0.01, 0.1]
}

grid_svc = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_svc.fit(X_train, y_train)

print('Best Parameters:', grid_svc.best_params_)
print('Best F1 Score:', grid_svc.best_score_)

KeyboardInterrupt:

# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

params = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_dt = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_dt.fit(X_train, y_train)

print('Best Parameters:', grid_dt.best_params_)
print('Best F1 Score:', grid_dt.best_score_)

Best Parameters: {'criterion': 'entropy', 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 5}
Best F1 Score: 0.8492375007276026

# RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

params = {
    'n_estimators': [100, 200],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid_rf = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

print('Best Parameters:', grid_rf.best_params_)
print('Best F1 Score:', grid_rf.best_score_)

Best Parameters: {'criterion': 'entropy', 'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 100}
Best F1 Score: 0.8615881168895789

# GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

params = {
    'var_smoothing': [1e-11, 1e-10, 1e-9, 1e-8, 1e-7]
}

grid_nb = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_nb.fit(X_train, y_train)

print('Best Parameters:', grid_nb.best_params_)
print('Best F1 Score:', grid_nb.best_score_)

Best Parameters: {'var_smoothing': 1e-11}
Best F1 Score: 0.8011788850688454

# GradientBoostingClassifier

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(random_state=42)

params = {
    'n_estimators': [150, 200, 250],
    'learning_rate': [0.05, 0.1],
    'max_depth': [4, 5, 6],
    'min_samples_leaf': [1, 2, 4]
}

grid_gb = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_gb.fit(X_train, y_train)

print('Best Parameters:', grid_gb.best_params_)
print('Best F1 Score:', grid_gb.best_score_)

KeyboardInterrupt:

# MLPClassifier

In [36]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(
    max_iter=1000,
    random_state=42
)

params = {
    'hidden_layer_sizes': [(50,), (100,), (50, 50)],
    'activation': ['relu', 'tanh'],
    'alpha': [0.0001, 0.001, 0.01]
}

grid_mlp = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_mlp.fit(X_train, y_train)

print('Best Parameters:', grid_mlp.best_params_)
print('Best F1 Score:', grid_mlp.best_score_)

Best Parameters: {'activation': 'relu', 'alpha': 0.001, 'hidden_layer_sizes': (50,)}
Best F1 Score: 0.7950253299560058

In [37]:
from sklearn.ensemble import HistGradientBoostingClassifier

model = HistGradientBoostingClassifier(
    random_state=42
)

params = {
    'learning_rate': [0.03, 0.05, 0.1],
    'max_iter': [100, 200, 300],
    'max_leaf_nodes': [15, 31, 63],
    'l2_regularization': [0, 0.1, 1]
}

grid_hgb = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=2
)

grid_hgb.fit(X_train, y_train)

print('Best Parameters:', grid_hgb.best_params_)
print('Best F1 Score:', grid_hgb.best_score_)

Best Parameters: {'l2_regularization': 1, 'learning_rate': 0.1, 'max_iter': 100, 'max_leaf_nodes': 31}
Best F1 Score: 0.86912825707746

In [39]:
from xgboost import XGBClassifier

model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.03, 0.05, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

grid_xgb = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=2
)

grid_xgb.fit(X_train, y_train)

print('Best Parameters:', grid_xgb.best_params_)
print('Best F1 Score:', grid_xgb.best_score_)

Best Parameters: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 5, 'n_estimators': 300, 'subsample': 1.0}
Best F1 Score: 0.871598322101654

In [40]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 5.9 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [41]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    random_state=42,
    verbose=0
)

params = {
    'iterations': [200, 300, 500],
    'depth': [4, 6, 8],
    'learning_rate': [0.03, 0.05, 0.1],
    'l2_leaf_reg': [1, 3, 5]
}

grid_cat = GridSearchCV(
    model,
    params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_cat.fit(X_train, y_train)

print('Best Parameters:', grid_cat.best_params_)
print('Best F1 Score:', grid_cat.best_score_)

Best Parameters: {'depth': 4, 'iterations': 500, 'l2_leaf_reg': 1, 'learning_rate': 0.1}
Best F1 Score: 0.8709050154815039

In [25]:
from xgboost import XGBClassifier
xgb_model = XGBClassifier(
    colsample_bytree=0.8,
    learning_rate=0.05,
    max_depth=5,
    n_estimators=300,
    subsample=1.0,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [26]:
y_pred = xgb_model.predict(X_test)

In [27]:

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8725170782974251
Precision: 0.7866876310272537
Recall: 0.6506285218899003
F1 Score: 0.7122182680901542

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.94      0.92      7208
           1       0.79      0.65      0.71      2307

    accuracy                           0.87      9515
   macro avg       0.84      0.80      0.82      9515
weighted avg       0.87      0.87      0.87      9515

In [28]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[6801  407]
 [ 806 1501]]

In [29]:
X.columns.tolist()

['age',
 'workclass',
 'fnlwgt',
 'education',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country']

In [63]:
user_data = {
    'age': 35,
    'workclass': 'Private',
    'fnlwgt': 180000,
    'education': 'Bachelors',
    'education-num': 13,
    'marital-status': 'Married-civ-spouse',
    'occupation': 'Exec-managerial',
    'relationship': 'Husband',
    'race': 'White',
    'sex': 'Male',
    'capital-gain': 0,
    'capital-loss': 0,
    'hours-per-week': 40,
    'native-country': 'United-States'
}

X_user = pd.DataFrame([user_data])

In [64]:
for col, le in label_encoders.items():
    X_user[col] = le.transform(X_user[col].astype(str))

In [65]:
X_user = pd.DataFrame(
    scaler.transform(X_user),
    columns=X_user.columns
)

In [66]:
probability = xgb_model.predict_proba(X_user)[0][1]

print(f"Income Probability: {probability:.2%}")

Income Probability: 67.61%

In [30]:
def predict_income(user_data):
    X_user = pd.DataFrame([user_data])
    for col, le in label_encoders.items():
        X_user[col] = le.transform(X_user[col].astype(str))
    X_user = X_user[X.columns]
    X_user = pd.DataFrame(
        scaler.transform(X_user),
        columns=X_user.columns
    )
    probability = xgb_model.predict_proba(X_user)[0][1]

    return probability

In [31]:
cars_df = pd.read_csv("data.csv")

In [32]:
def get_affordable_cars(probability, cars_df):

    if probability < 0.20:
        max_bin = 0.0

    elif probability < 0.40:
        max_bin = 0.2

    elif probability < 0.60:
        max_bin = 0.4

    elif probability < 0.80:
        max_bin = 0.6

    else:
        max_bin = 0.8

    affordable_cars = cars_df[
        cars_df['price_bin'] <= max_bin
    ].copy()

    return affordable_cars

In [33]:
def filter_cars(
    cars_df,
    brand=None,
    model=None,
    min_year=None,
    condition=None,
    fuel_type=None,
    color=None,
    location=None
):

    filtered = cars_df.copy()

    if brand:
        filtered = filtered[filtered['brand'] == brand]

    if model:
        filtered = filtered[filtered['model'] == model]

    if min_year:
        filtered = filtered[filtered['year'] >= min_year]

    if condition:
        filtered = filtered[filtered['condition'] == condition]

    if fuel_type:
        filtered = filtered[filtered['fuel_type'] == fuel_type]

    if color:
        filtered = filtered[filtered['color'] == color]

    if location:
        filtered = filtered[filtered['location'] == location]

    return filtered